title: 배우는 모든 것
author:
  name: 유나
  email: mathematike6@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
mathema:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: mathematike
    github:  mathematike
    # devto: mathematike
    # dribbble: mathematike
    # facebook: mathematike
    # flickr:   mathematike
    # instagram: mathematike
    # linkedin: mathematike
    # pinterest: mathematike
    # youtube: mathematike
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: mathematike
    # googleplus: +mathematike
    # microdotblog: mathematike
    # keybase: mathematike

    # Mastodon instances
    # mastodon:
    # - username: mathematike
    #   instance: example.com
    # - username: mathematike2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: mathematike
    #   instance: example.com
    # - username: mathematike2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: mathema

plugins:
 - jekyll-feed
 - jekyll-seo-tag
